### ISSUE TITLE
Disconnection after sending or receiving messages...

### ISSUE THREAD

**Issue by Ing-Rigyu** [biohazardxxx/ESP_WiFiSwitch#1]
Have been testing your awesome project but have found some bug...

The client connects successfully but after some message it drops the connection.

This is a sample output, have tested with 3 different servers. ¿Any help?

 .....
WiFi connected
Connecting to MQTT server test.mosquitto.org as WiFiSwitch-18:fe:34:9f:9b:30
Connected to MQTT broker
Subsribed to topic.
MQTT message arrived:  topic: test message: 1
Light is 0
Switching light to high
MQTT message arrived:  topic: test message: 1
Light is 1
Switching light to high
Connecting to MQTT server test.mosquitto.org as WiFiSwitch-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30
MQTT connect failed! 
Connecting to MQTT server test.mosquitto.org as WiFiSwitch-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30
MQTT connect failed! 
Connecting to MQTT server test.mosquitto.org as WiFiSwitch-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30
MQTT connect failed! 
Connecting to MQTT server test.mosquitto.org as WiFiSwitch-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30-18:fe:34:9f:9b:30

Also tested in a private sever with mosquitto 1.4.2.

**Comment by biohazardxxx** [comment]
Hi,
I'm using mosquito 1.3.1 on debian. Can you try with that Version? I'm not
sure yet what versions are supported by pubsubclient.
Br
Bio
Am 11.07.2015 3:57 vorm. schrieb "Rigyu" notifications@github.com:

**Comment by Ing-Rigyu** [comment]
Used mosquito 1.3.1 debian install... same result. It connects 5 ~ 10 seconds, then it goes forever in "Connecting to [...]..."

EDIT: Server reports "Socket read error on client" when disconnecting

**Comment by Ing-Rigyu** [comment]
SOLVED. Was my router fault. I have a TP-Link "TL-WR741ND" with bgn mixed mode selected, changed to use only b and now the connection it's ok. Thank you for your time.

**Comment by biohazardxxx** [comment]
Glad you solved it!
