### ISSUE TITLE
mqtt works perfectly but http code hangs after a few minutes

### ISSUE THREAD

**Issue by rajbadri** [biohazardxxx/ESP_WiFiSwitch#2]
hi
i tested a relay connected to the esp8266 in mqtt mode and the setup ran perfectly for days but when i put the esp in http mode it stops responding after a few minutes.

**Comment by biohazardxxx** [comment]
Hi,
I could not recreate your described issue.
(18:58:52.25) Startup
(18:58:52.40) Connecting to WiFi ABCD
(18:58:52.48) Wifi test...
(18:58:53.49) .......
(18:58:56.50) WiFi connected
(18:58:56.50) mDNS responder started
(18:58:56.50) 192.168.0.144
(18:58:56.50) Web server started
(18:59:30.27) Light switched via web request to  1
(18:59:33.69) Light switched via web request to  0
(19:03:07.47) Sending 200
(19:07:04.14) Light switched via web request to  1
(19:07:08.30) Light switched via web request to  0
(19:12:18.89) Light switched via web request to  1
(19:12:23.19) Light switched via web request to  0
(19:34:31.24) Light switched via web request to  1
(19:34:33.09) Light switched via web request to  0
(19:41:24.45) Light switched via web request to  1
(19:41:26.27) Light switched via web request to  0
(19:41:28.14) Light switched via web request to  1
(19:41:29.65) Light switched via web request to  0
(19:41:31.49) Light switched via web request to  1
(19:41:34.57) Light switched via web request to  0
(19:52:16.65) Light switched via web request to  1
(19:52:18.47) Light switched via web request to  0

I've just added more logging to the sketch for this issue. Do you get anything on serial? Can you check your DHCP leas time? I think it is something specific to your network environment.

**Comment by biohazardxxx** [comment]
I assume you lost the interest or could fix your problem meanwhile so I'm closing this issue.
