### ISSUE TITLE
intial setup page does not recognise full address

### ISSUE THREAD

**Issue by rajbadri** [biohazardxxx/ESP_WiFiSwitch#4]
hi i can use mqtt when in the initial setup page i give the ip address of the broker 
example : 212.72.74.21
but if i give the full name : "broker.mqttdashboard.com"    it truncates it to "broker.mqttdashboard"  and does not connect to the broker

**Comment by rajbadri** [comment]
i tried it with "test.mosquitto.org" and it truncates it to "test.mosquito"

**Comment by biohazardxxx** [comment]
Ok. I'll check that next days
Am 22.08.2015 12:29 nachm. schrieb "Raj Badri" notifications@github.com:

**Comment by biohazardxxx** [comment]
The reason is that it is using only 15 characters.
I need to change the html input element to have "maxlength" instead of
"length", so only 15 chars can be entered.
A future version will except more.

2015-08-23 11:46 GMT+02:00 Alex Schick al3x.5ch1ck@gmail.com:

**Comment by biohazardxxx** [comment]
This is fixed with using SPIFF.
