### ISSUE TITLE
Fritzing picture

### ISSUE THREAD

**Issue by rajbadri** [biohazardxxx/ESP_WiFiSwitch#5]
hi
i have ordered pcb of your design from osh-park. but being a novice don't get the layout of button correctly. if you can post a fritzing picture of your design it will be of great help. Also can i replace the Triac BT136D with BT136

thanks for your help

Raj

**Comment by rajbadri** [comment]
solved it and now works like a charm

![wifi-switch](https://cloud.githubusercontent.com/assets/5882232/11163761/683dbcb6-8b01-11e5-96c7-3c8237ef0e66.jpg)

**Comment by biohazardxxx** [comment]
Hi, sorry for late reply! Happy you could work it out. Would it be ok with you if I place the fritzing picture on the main readme of the repository? It might also help others.

**Comment by rajbadri** [comment]
yes please do so
and can you please give me link for a/c fuse to use with this switch

Thanks

**Comment by biohazardxxx** [comment]
thank you. No I can't since in europe we have the whole rome power line on one fuse. Some have per lights but not for only one light. However this switch itself has a current below 1000mA. Then it depends on your light.
