### ISSUE TITLE
Getting error while compiling

### ISSUE THREAD

**Issue by rajbadri** [biohazardxxx/ESP_WiFiSwitch#7]
getting this error while compiling

Arduino: 1.6.5 (Mac OS X), Board: "Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 115200, 4M (3M SPIFFS)"

Using library ESP8266WiFi in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WiFi 
Using library ESP8266mDNS in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266mDNS (legacy)
Using library ESP8266WebServer in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer 
Using library Ticker in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/Ticker 
Using library PubSubClient in folder: /Users/rajbadri/Documents/Arduino/libraries/pubsubclient-2.4 
Using library ArduinoJson in folder: /Users/rajbadri/Documents/Arduino/libraries/ArduinoJson 

/Users/rajbadri/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/tools/sdk//include -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10605 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DESP8266 -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/cores/esp8266 -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/variants/generic -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WiFi/src -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266mDNS -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer/src -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/Ticker -I/Users/rajbadri/Documents/Arduino/libraries/pubsubclient-2.4/src -I/Users/rajbadri/Documents/Arduino/libraries/ArduinoJson/src /var/folders/hg/jblrvjks6tl65wsrsc7fs9c00000gn/T/build399527398758220727.tmp/ESP_WiFiSwitch.cpp -o /var/folders/hg/jblrvjks6tl65wsrsc7fs9c00000gn/T/build399527398758220727.tmp/ESP_WiFiSwitch.cpp.o 
serverFunctions.ino: In function 'void launchWeb(int)':
serverFunctions.ino:136:8: error: no matching function for call to 'ESP8266WebServer::on(const char [8], HTTPMethod, launchWeb(int)::__lambda1, launchWeb(int)::__lambda2)'
serverFunctions.ino:136:8: note: candidates are:
In file included from ESP_WiFiSwitch.ino:45:0:
/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:60:8: note: void ESP8266WebServer::on(const char_, ESP8266WebServer::THandlerFunction)
   void on(const char_ uri, THandlerFunction handler);
        ^
/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:60:8: note:   candidate expects 2 arguments, 4 provided
/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:61:8: note: void ESP8266WebServer::on(const char_, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char_ uri, HTTPMethod method, THandlerFunction fn);
        ^
/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:61:8: note:   candidate expects 3 arguments, 4 provided
serverFunctions.ino:167:22: error: 'class PubSubClient' has no member named 'setBrokerDomain'
serverFunctions.ino:168:22: error: 'class PubSubClient' has no member named 'setPort'
no matching function for call to 'ESP8266WebServer::on(const char [8], HTTPMethod, launchWeb(int)::__lambda1, launchWeb(int)::__lambda2)'

Please guide
Thanks

**Comment by biohazardxxx** [comment]
Hi,

please use latest staging version 2.0.0-rc2 of ESP8266 arduino package.
Also If you are using an ESP-03 please use flash settings: 1M

**Comment by rajbadri** [comment]
still getting the same error after update

Arduino: 1.6.5 (Mac OS X), Board: "Generic ESP8266 Module, Serial, 80 MHz, 40MHz, DIO, 115200, 4M (3M SPIFFS)"

Using library ESP8266WiFi in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WiFi 
Using library ESP8266mDNS in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266mDNS (legacy)
Using library ESP8266WebServer in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer 
Using library Ticker in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/Ticker 
Using library PubSubClient in folder: /Users/rajbadri/Documents/Arduino/libraries/pubsubclient 
Using library ArduinoJson in folder: /Users/rajbadri/Documents/Arduino/libraries/ArduinoJson 

/Users/rajbadri/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/tools/sdk//include -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10605 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DESP8266 -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/cores/esp8266 -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/variants/generic -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WiFi/src -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266mDNS -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer/src -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/Ticker -I/Users/rajbadri/Documents/Arduino/libraries/pubsubclient/src -I/Users/rajbadri/Documents/Arduino/libraries/ArduinoJson/src /var/folders/hg/jblrvjks6tl65wsrsc7fs9c00000gn/T/build1018353757235617151.tmp/ESP_WiFiSwitch.cpp -o /var/folders/hg/jblrvjks6tl65wsrsc7fs9c00000gn/T/build1018353757235617151.tmp/ESP_WiFiSwitch.cpp.o 
serverFunctions.ino: In function 'void launchWeb(int)':
serverFunctions.ino:136:8: error: no matching function for call to 'ESP8266WebServer::on(const char [8], HTTPMethod, launchWeb(int)::__lambda1, launchWeb(int)::__lambda2)'
serverFunctions.ino:136:8: note: candidates are:
In file included from ESP_WiFiSwitch.ino:45:0:
/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:60:8: note: void ESP8266WebServer::on(const char_, ESP8266WebServer::THandlerFunction)
   void on(const char_ uri, THandlerFunction handler);
        ^
/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:60:8: note:   candidate expects 2 arguments, 4 provided
/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819f0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:61:8: note: void ESP8266WebServer::on(const char_, HTTPMethod, ESP8266WebServer::THandlerFunction)
   void on(const char_ uri, HTTPMethod method, THandlerFunction fn);
        ^
/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.5-947-g39819

f0/libraries/ESP8266WebServer/src/ESP8266WebServer.h:61:8: note:   candidate expects 3 arguments, 4 provided
serverFunctions.ino:167:22: error: 'class PubSubClient' has no member named 'setBrokerDomain'
serverFunctions.ino:168:22: error: 'class PubSubClient' has no member named 'setPort'
no matching function for call to 'ESP8266WebServer::on(const char [8], HTTPMethod, launchWeb(int)::__lambda1, launchWeb(int)::__lambda2)'

![screen shot 2015-12-13 at 2 39 54 pm](https://cloud.githubusercontent.com/assets/5882232/11766308/6eaa582c-a1a7-11e5-9cfb-7258b4ddd9d9.png)

**Comment by biohazardxxx** [comment]
Did you restart arduino IDE after update?

**Comment by biohazardxxx** [comment]
I'll close this now. Let me know if you still need help.
