### ISSUE TITLE
getting error when compiling please help

### ISSUE THREAD

**Issue by rajbadri** [biohazardxxx/ESP_WiFiSwitch#8]
all this while i am using the older version of your sketch. and it works perfectly

trying to compile the new version but it gives error

![screen shot 2016-01-07 at 9 31 50 am](https://cloud.githubusercontent.com/assets/5882232/12161930/8a2cddb2-b521-11e5-8324-4e3cf13fff9a.png)

the detailed error message is

Arduino: 1.6.5 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

Build options changed, rebuilding all
Using library ESP8266WiFi in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266WiFi 
Using library ESP8266mDNS in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266mDNS (legacy)
Using library ESP8266WebServer in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266WebServer 
Using library Ticker in folder: /Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/Ticker 
Using library PubSubClient in folder: /Users/rajbadri/Documents/Arduino/libraries/PubSubClient (legacy)
Using library ArduinoJson in folder: /Users/rajbadri/Documents/Arduino/libraries/ArduinoJson (legacy)

/Users/rajbadri/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/tools/sdk/include -c -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DARDUINO=10605 -DARDUINO_ESP8266_ESP12 -DARDUINO_ARCH_ESP8266 -DESP8266 -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/cores/esp8266 -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/variants/nodemcu -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266WiFi/src -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266mDNS -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/ESP8266WebServer/src -I/Users/rajbadri/Library/Arduino15/packages/esp8266/hardware/esp8266/2.1.0-rc1/libraries/Ticker -I/Users/rajbadri/Documents/Arduino/libraries/PubSubClient -I/Users/rajbadri/Documents/Arduino/libraries/ArduinoJson /var/folders/hg/jblrvjks6tl65wsrsc7fs9c00000gn/T/build989273569338910562.tmp/ESP_WiFiSwitch.cpp -o /var/folders/hg/jblrvjks6tl65wsrsc7fs9c00000gn/T/build989273569338910562.tmp/ESP_WiFiSwitch.cpp.o 
ConfigFunctions.ino: In function 'bool loadConfig()':
ConfigFunctions.ino:31:29: error: conversion from 'ArduinoJson::JsonVariant' to non-scalar type 'String' requested
ConfigFunctions.ino:32:31: error: conversion from 'ArduinoJson::JsonVariant' to non-scalar type 'String' requested
ConfigFunctions.ino:34:37: error: conversion from 'ArduinoJson::JsonVariant' to non-scalar type 'String' requested
ConfigFunctions.ino:35:37: error: conversion from 'ArduinoJson::JsonVariant' to non-scalar type 'String' requested
ConfigFunctions.ino:36:41: error: conversion from 'ArduinoJson::JsonVariant' to non-scalar type 'String' requested
conversion from 'ArduinoJson::JsonVariant' to non-scalar type 'String' requested

i am using arduino ide 1.6.5 and boards version 2.1.0-rc1

Please guide

Thanks

**Comment by biohazardxxx** [comment]
Hi, 
Please remobe the esp package via boards manager in the IDE and then install latest staging again. This helped a few times.
