### ISSUE TITLE
PubSubClient.setBrokerDomain error

### ISSUE THREAD

**Issue by scottjgibson** [biohazardxxx/ESP_WiFiSwitch#9]
I'm receiving the following compilation errors (I'm using the pubsub library you referenced)

serverFunctions:167: error: 'class PubSubClient' has no member named 'setBrokerDomain'
serverFunctions:168: error: 'class PubSubClient' has no member named 'setPort'

Any thoughts?  I'm porting it the ecoPlug switch in place of the basic firmware I wrote.
http://thegreatgeekery.blogspot.ca/2016/02/ecoplug-wifi-switch-hacking.html

**Comment by biohazardxxx** [comment]
Sorry for the late reply.
I've zipped the PubSub library folder that I use for you:
https://www.dropbox.com/s/iedjiuyauiibkcm/PubSubClient_WiFiSwitch.zip?dl=0

**Comment by odedtgr** [comment]
Running into the same issue. DropBox link is outdated.
Can you assist?
Thanks,

**Comment by biohazardxxx** [comment]
Hi,
Sorry!
new link: https://dl.dropboxusercontent.com/u/23413755/PubSubClient_WiFiSwitch.zip

Best regards
-Alex
